Almost complete amd64 EFI support:
 * If we're using xorriso, include the FAT partition containing the
   EFI loader, so now we will boot off USB too \o/
 * Rearrange the order of the script for clarity
 * Add more comments explaining what we're doing

diff --git a/tools/boot/wheezy/boot-x86 b/tools/boot/wheezy/boot-x86
--- a/tools/boot/wheezy/boot-x86
+++ b/tools/boot/wheezy/boot-x86
@@ -51,16 +51,6 @@ if [ $NN != 1 ] ; then exit 0; fi
 INSTALLDIR_i386="install.386"
 INSTALLDIR_amd64="install.amd"
 
-case "$MKISOFS" in
-    *xorriso*)
-        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-isohybrid-mbr syslinux/usr/lib/syslinux/isohdpfx.bin"
-        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_offset 16"
-# uncoment to add a small FAT partition on the media
-#        /sbin/mkfs.msdos -n Bla -C test.fat 8192
-#      add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0x01 test.fat"
-       ;;
-esac
-
 if [ "$ARCH" = i386 ]; then
 	INSTALLDIR="$INSTALLDIR_i386"
 else
@@ -195,49 +185,14 @@ fi
 echo $SYSLINUXDEB >> $CDDIR/../$N.pkgs_extracted
 find_pkg_file syslinux source >> $CDDIR/../$N.pkgs_extracted
 
-if [ "$ARCH" = amd64 ]; then
-    mkdir -p $CDDIR/../grub-efi
-    GRUB_EFI_DEB=$(find_pkg_file grub-efi-amd64-bin)
-    if [ -z "$GRUB_EFI_DEB" ]; then
-	    echo "ERROR: grub-efi-amd64-bin package is required" >&2
-	    exit 1
-    fi
-    (dpkg --fsys-tarfile "$MIRROR/$GRUB_EFI_DEB" | \
-	    tar xf - -C $CDDIR/../grub-efi)
-
-    GRUB_COMMON_DEB=$(find_pkg_file grub-common)
-    if [ -z "$GRUB_COMMON_DEB" ]; then
-	    echo "ERROR: grub-common package is required" >&2
-	    exit 1
-    fi
-    (dpkg --fsys-tarfile "$MIRROR/$GRUB_COMMON_DEB" | \
-	    tar xf - -C $CDDIR/../grub-efi)
-
-    # We're including bits from the grub-efi-amd64-bin package
-    echo $GRUB_EFI_DEB >> $CDDIR/../$N.pkgs_extracted
-    find_pkg_file grub-efi-amd64-bin source >> $CDDIR/../$N.pkgs_extracted
-
-    # But *not* from grub-common, we're just using grub-mkimage in the build
-
-    # Create a bootable EFI GRUB image
-    $BASEDIR/tools/efi-image $CDDIR/../efi-tmp x86_64-efi x64 $CDDIR/../grub-efi
-
-    # Now move the GRUB files to the right place.
-    mkdir -p $CDDIR/efi/boot
-    mcopy -i $CDDIR/../efi-tmp/efi.img ::efi/boot/bootx64.efi $CDDIR/efi/boot/bootx64.efi
-    mkdir -p $CDDIR/boot/grub
-    cp -a $CDDIR/../efi-tmp/efi.img $CDDIR/boot/grub
-    cp -a $CDDIR/../efi-tmp/boot/grub/* $CDDIR/boot/grub/
-    cp -a $CDDIR/../grub-efi/usr/share/grub/*pf2 $CDDIR/boot/grub
-    cp -a $BASEDIR/data/wheezy/grub.cfg $CDDIR/boot/grub
-    case "$MKISOFS" in
-        *xorriso*)
-            add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-eltorito-alt-boot --efi-boot boot/grub/efi.img";;
-        *)
-            add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "--eltorito-alt-boot --efi-boot boot/grub/efi.img";;
-    esac
-#    sed -i '/^menuentry/Q' $CDDIR/boot/grub/grub.cfg
-fi
+# If we're using xorriso, use its isohybrid code to make an image
+# BIOS-bootable for a USB stick as well as via ElTorito for a CD/DVD
+case "$MKISOFS" in
+    *xorriso*)
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-isohybrid-mbr syslinux/usr/lib/syslinux/isohdpfx.bin"
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_offset 16"
+       ;;
+esac
 
 # In case of a multi-arch CD the script will be called two times. The
 # first time the isolinux dir gets set up for single arch; if it is
@@ -412,15 +367,84 @@ fi
 
 rm -rf cdrom floppy
 
+# Common mkisofs options when creating CDs
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
+
+# Add the normal options to make an ElTorito bootable CD/DVD
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b isolinux/isolinux.bin"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c isolinux/boot.cat"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot"
-
 bls=$(calc_boot_size "boot$N/isolinux/isolinux.bin")
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-load-size $bls"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-info-table"	
+
+# We explicitly put the boot bits in boot$N (as opposed to CD$N) and
+# list it first on the eventual mkisofs command line. That means
+# they'll be placed nearer the front of the eventual image; some older
+# BIOSes apparently have a limitation on what they'll boot here.
 add_mkisofs_opt $CDDIR/../$N.mkisofs_dirs "boot$N"
+
+# For amd64, add EFI boot options too. Could probably do this for i386
+# as well if desired, but it's not such a priority. There aren't that
+# many i386 EFI machines around, after all...
+if [ "$ARCH" = amd64 ]; then
+
+    # Extract bits from a couple of grub packages that we'll need to
+    # use
+    mkdir -p $CDDIR/../grub-efi
+    GRUB_EFI_DEB=$(find_pkg_file grub-efi-amd64-bin)
+    if [ -z "$GRUB_EFI_DEB" ]; then
+	    echo "ERROR: grub-efi-amd64-bin package is required" >&2
+	    exit 1
+    fi
+    (dpkg --fsys-tarfile "$MIRROR/$GRUB_EFI_DEB" | \
+	    tar xf - -C $CDDIR/../grub-efi)
+
+    GRUB_COMMON_DEB=$(find_pkg_file grub-common)
+    if [ -z "$GRUB_COMMON_DEB" ]; then
+	    echo "ERROR: grub-common package is required" >&2
+	    exit 1
+    fi
+    (dpkg --fsys-tarfile "$MIRROR/$GRUB_COMMON_DEB" | \
+	    tar xf - -C $CDDIR/../grub-efi)
+
+    # We're including bits from the grub-efi-amd64-bin package
+    echo $GRUB_EFI_DEB >> $CDDIR/../$N.pkgs_extracted
+    find_pkg_file grub-efi-amd64-bin source >> $CDDIR/../$N.pkgs_extracted
+
+    # But *not* from grub-common, we're just using grub-mkimage in the build
+
+    # Create a bootable EFI GRUB image that we can use
+    $BASEDIR/tools/efi-image $CDDIR/../efi-tmp x86_64-efi x64 $CDDIR/../grub-efi
+
+    # Now move the GRUB files to the right place in the CD image
+    mkdir -p $CDDIR/efi/boot
+    mcopy -i $CDDIR/../efi-tmp/efi.img ::efi/boot/bootx64.efi $CDDIR/efi/boot/bootx64.efi
+    mkdir -p $CDDIR/boot/grub
+    cp -a $CDDIR/../efi-tmp/efi.img $CDDIR/boot/grub
+    cp -a $CDDIR/../efi-tmp/boot/grub/* $CDDIR/boot/grub/
+    cp -a $CDDIR/../grub-efi/usr/share/grub/*pf2 $CDDIR/boot/grub
+    cp -a $BASEDIR/data/wheezy/grub.cfg $CDDIR/boot/grub
+    # TODO: generate the grub menu entries, or grab pre-made ones from a d-i build
+
+    case "$MKISOFS" in
+        *xorriso*)
+
+            # Tell xorriso to create a secondary ElTorito boot record
+            # for the EFI bootloader
+            add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-eltorito-alt-boot --efi-boot boot/grub/efi.img"
+
+            # Add the efi image as a FAT partition too, so our CD
+            # image will also boot on a USB key (like isohybrid, just
+            # implemented differently)
+            add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0x01 $CDDIR/../efi-tmp/efi.img"
+            ;;
+
+        *)
+            add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "--eltorito-alt-boot --efi-boot boot/grub/efi.img"
+            ;;
+    esac
+fi # if ARCH == amd64
 
 # th,th, thats all
