checkin of last config before removal on farbror

diff --git a/sarge/tools/generate_di+k_list b/sarge/tools/generate_di+k_list
--- a/sarge/tools/generate_di+k_list
+++ b/sarge/tools/generate_di+k_list
@@ -41,67 +41,94 @@ jfsutils
 reiserfsprogs
 libfribidi0
 localization-config
-acpid
-initramfs-tools
-
 #ifdef ARCH_i386
 discover
 discover1
 grub
 lilo
-/* Note that we do not have to include every optimised kernel flavor for
- * i386. Kernel headers are included as third party modules are commonly
- * used on this architecture.
- */
-kernel-image-2.4-386
-kernel-pcmcia-modules-2.4-386
-kernel-headers-2.4-386
-linux-image-2.6-386
-linux-headers-2.6-386
-#endif
+EOF
 
+/bin/sed -n 's/Package: \(kernel-image-2.4.*-386\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
+  >> debian-installer+kernel-$DI_CODENAME
+/bin/sed -n 's/Package: \(kernel-pcmcia-modules-2.4.*-386\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
+  >> debian-installer+kernel-$DI_CODENAME
+/bin/sed -n 's/Package: \(kernel-image-2.6.*-386\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
+  >> debian-installer+kernel-$DI_CODENAME
+
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_amd64
 discover
 discover1
 grub
 lilo
-linux-image-2.6-amd64-generic
-linux-headers-2.6-amd64-generic
-#endif
+EOF
 
+if [ ! -e $MIRROR/dists/$CODENAME/main/binary-amd64/Packages ]; then
+	echo "Cannot find amd64 packages file, inserting static entry as workaround" >&2
+	echo kernel-image-2.6.8-11-amd64-generic >> debian-installer+kernel-$DI_CODENAME
+else
+	/bin/sed -n 's/Package: \(kernel-image-2.6.*-generic\)$/\1/p' \
+	  $MIRROR/dists/$CODENAME/main/binary-amd64/Packages|/usr/bin/tail -n 1 \
+	  >> debian-installer+kernel-$DI_CODENAME
+	/bin/sed -n 's/Package: \(kernel-pcmcia-modules-2.6.*-generic\)$/\1/p' \
+	  $MIRROR/dists/$CODENAME/main/binary-amd64/Packages|/usr/bin/tail -n 1 \
+	  >> debian-installer+kernel-$DI_CODENAME
+fi
+	 
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_alpha
 aboot
 aboot-base
 discover1
-kernel-image-2.4-generic
-kernel-image-2.4-smp
-#endif
+EOF
 
+/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-alpha/Packages|grep -v 2.4.21 \
+  >> debian-installer+kernel-$DI_CODENAME
+
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_hppa
 discover1
-linux-image-2.6-parisc
-linux-image-2.6-parisc-smp
-linux-image-2.6-parisc64
-linux-image-2.6-parisc64-smp
-#endif
+EOF
 
+/bin/sed -n 's/Package: \(kernel-image-2.6.*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-hppa/Packages|tail -n4 \
+  >> debian-installer+kernel-$DI_CODENAME
+
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_ia64
 discover1
 initrd-tools
-linux-image-2.6-itanium
-linux-image-2.6-itanium-smp
-linux-image-2.6-mckinley
-linux-image-2.6-mckinley-smp
-#endif
+EOF
 
+/bin/sed -n 's/Package: \(kernel-image-2\.4\..*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages | tail -n 4 \
+  >> debian-installer+kernel-$DI_CODENAME
+/bin/sed -n 's/Package: \(kernel-image-2\.4-.*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages \
+  >> debian-installer+kernel-$DI_CODENAME
+/bin/sed -n 's/Package: \(kernel-image-2\.6\..*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages | tail -n 4 \
+  >> debian-installer+kernel-$DI_CODENAME
+/bin/sed -n 's/Package: \(kernel-image-2\.6-.*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages \
+  >> debian-installer+kernel-$DI_CODENAME
+
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_mips
 arcboot
 EOF
 
 # Only include mips kernels that d-i base-installer installs.
-# XXX once mips gets kernel-image-2.4-<subarch> packages, use those
-# instead.
-for subarch in r4k-ip22 r5k-ip22 sb1-swarm-bn; do
+for subarch in r4k-ip22 r5k-ip22; do
 	sed -n 's/Package: \(kernel-image-.*-.*\)$/\1/p' \
 		$MIRROR/dists/$CODENAME/main/binary-mips/Packages \
 		| grep -- "-$subarch$" | sort -n | tail -n 1 \
@@ -110,15 +137,12 @@ done
 
 cat >> debian-installer+kernel-$DI_CODENAME << EOF
 #endif
-
 #ifdef ARCH_mipsel
 delo
 EOF
 
 # Only include mipsel kernels that d-i base-installer installs.
-# XXX once mips gets kernel-image-2.4-<subarch> packages, use those
-# instead.
-for subarch in r3k-kn02 r4k-kn04 cobalt lasat; do
+for subarch in r3k-kn02 r4k-kn04; do
 	sed -n 's/Package: \(kernel-image-.*-.*\)$/\1/p' \
 		$MIRROR/dists/$CODENAME/main/binary-mipsel/Packages \
 		| grep -- "-$subarch$" | sort -n | tail -n 1 \
@@ -127,23 +151,16 @@ done
 
 cat >> debian-installer+kernel-$DI_CODENAME << EOF
 #endif
-
 #ifdef ARCH_powerpc
 discover1
 quik
 yaboot
-hfsutils
 mkvmlinuz
 module-init-tools
 initrd-tools
-linux-image-2.6-powerpc
-linux-image-2.6-powerpc-smp
-linux-image-2.6-powerpc64
 EOF
 
 # Only include powerpc kernels that d-i base-installer installs.
-# XXX once powerpc 2.4 gets kernel-image-2.4-<subarch> packages, use those
-# instead, but beware of apus.
 for subarch in powerpc power3 power4 power3-pmac power3-chrp-rs6k \
 		power4-pmac power4-chrp-rs6k powerpc-pmac \
 		powerpc-prep powerpc-chrp powerpc-chrp-rs6k apus; do
@@ -155,30 +172,27 @@ done
 
 cat >> debian-installer+kernel-$DI_CODENAME << EOF
 #endif
-
 #ifdef ARCH_sparc
 discover1
 initrd-tools
-linux-image-2.6-sparc64
-linux-image-2.6-sparc64-smp
-kernel-image-2.4-sparc32
-kernel-image-2.4-sparc32-smp
-kernel-image-2.4-sparc64
-kernel-image-2.4-sparc64-smp
-#endif
+EOF
 
+/bin/sed -n 's/Package: \(kernel-image-.*-sparc.*\)$/\1/p' \
+  $MIRROR/dists/$CODENAME/main/binary-sparc/Packages \
+  >> debian-installer+kernel-$DI_CODENAME
+
+cat >> debian-installer+kernel-$DI_CODENAME << EOF
+#endif
 #ifdef ARCH_m68k
 fileutils
 EOF
 
 # Get all the latest 2.2 for mac kernel
-sed -n 's/Package: \(kernel-image-2.2.*-mac\)$/\1/p' \
+/bin/sed -n 's/Package: \(kernel-image-2.2.*-mac\)$/\1/p' \
   $MIRROR/dists/$CODENAME/main/binary-m68k/Packages | tail -n 1 \
   >> debian-installer+kernel-$DI_CODENAME
 # Get the latest 2.4 kernels, except mac
-# XXX once m68k gets kernel-image-2.4-<subarch> packages, use those
-# instead.
-sed -n 's/Package: \(kernel-image-2.4.*\)$/\1/p' \
+/bin/sed -n 's/Package: \(kernel-image-2.4.*\)$/\1/p' \
   $MIRROR/dists/$CODENAME/main/binary-m68k/Packages | tail -n 7 | \
   grep -v mac >> debian-installer+kernel-$DI_CODENAME
 
@@ -188,7 +202,7 @@ cat >> debian-installer+kernel-$DI_CODENAME << EOF
 discover1
 EOF
 
-sed -n 's/Package: \(kernel-image-2.4.*\)$/\1/p' \
+/bin/sed -n 's/Package: \(kernel-image-2.4.*\)$/\1/p' \
   $MIRROR/dists/$CODENAME/main/binary-arm/Packages|tail -n5 \
   >> debian-installer+kernel-$DI_CODENAME
 
